- name:  Deploy project
  hosts: localhost
  gather_facts: false
  tasks:
  - name:  use expect from localhost
    expect:
       command: ssh admin@appqa-4-05
       responses:
         'Password:': "injab0xn"
         '>' : "enable"
         '#' : "show version"
         '#' : "exit"
