- name: Get Status 
  hosts: localhost
  connection: local
  tasks:
    - name: man update
      uri:
        method: GET
        url: "https://x.x.x.x/xxxxxxx/rest/v1.0/actions/manufacture"
        return_content: yes
        headers:
          Accept: application/json
          Accept-Encoding: gzip, deflate, br
          Connection: keep-alive
          Cookie: session_minerva=9e805706-65eb-489a-9598-3fc4edb9a28c; remember_token="mofassir.haque\073\073\073426809eb45d15779ec490b70fb8de94e6eec2300050946c95e300498a2ea4d4f|ff127db3e8763a83d87b5623435789b42b179749dd7704ae5bbef6396111459fe576a1f04b755f18e0573ecc45469af8a74f83a478c53dd4eba45e7b331b57a0"
      register: response

    - debug:
        msg: "{{ response.content }}"
