- name: Login requests
  hosts: localhost
  connection: local
  tasks:
    - name: Login request
      uri:
        method: POST
        url: "https://xxxxxx.xxxx.xxxxx.xxxxx.xxx/xxxxxx/rest/v1.0/login"
        return_content: yes
        headers:
          Accept: application/json
          Accept-Encoding: gzip, deflate, br
          Connection: keep-alive
          Cookie: remember_token="mofassir.haque\073\073\0736de230b30411cb2a57ebd2b0f48bcd15f5b7380445c3d2940a6ecd42c67765e6|f3e9d8f2c150c10b504ca7694408c107656d43e5b6cc66efca641342c88e1bc85b3cce65f112a76542f0b6ca79678bd0e1ee3a5f9dfb7ebb5122db203871f6a5"; session_minerva=fb602f8d-385d-444d-bf19-0532d17158f2
          Sec-Fetch-Dest: empty
          Sec-Fetch-Mode: cors
          Sec-Fetch-Site: same-origin
          
        body_format: json 
        body:
           username: "xxxxxxxxxxxxxxxx"
           password: "xxxxxxxxxxxxxxxxxxx"
           timeout: 3600

      register: response

    - debug:
        msg: "{{ response.content }}"
